### ISSUE TITLE
Bot should not reply to itself

### ISSUE THREAD

**Issue by kpman** [bottenderjs/bottender-fb#2]
The public reply will trigger the same event bot subscribed.
And the result is like the following snippet:
```
{ error:
   { message: '(#10903) This user cant reply to this activity',
     type: 'OAuthException',
     code: 10903,
     fbtrace_id: 'DmINzGE2Evu' } }
```

**Comment by tw0517tw** [comment]
How should we do this?
Silently fails with no message? Show a warning message and not sending request?
